<?php
$locationArray = array('delhi'=>'Delhi','bang'=>'Bengaluru / Bangalore','mumbai'=>'Mumbai','hydrabaad'=>'Hyderabad / Secunderabad','chn'=>'Chennai','mohali'=>'Mohali','surat'=>'Surat','gurgaon'=>'Gurgaon','shimla'=>'Shimla','calicut'=>'Calicut','cochin'=>'Cochin','kochi'=>'Kochi','bhopal'=>'Bhopal','gwalior'=>'Gwalior','indore'=>'Indore','jabalpur'=>'Jabalpur','ujjain'=>'Ujjain','nagpur'=>'Nagpur','nasik'=>'Nasik','pune'=>'Pune','chandigarh'=>'Chandigarh','jaipur'=>'Jaipur','kota'=>'Kota','agra'=>'Agra','kanpur'=>'Kanpur','lucknow'=>'Lucknow','noida'=>'Noida','ghaziabaad'=>'Ghaziabaad','allahabad'=>'Allahabad','mathura'=>'Mathura','roorkee'=>'Roorkee','dehradun'=>'Dehradun','bhubaneswar'=>'Bhubaneswar','cuttack'=>'Cuttack','puri'=>'Puri','rourkela'=>'Rourkela','kolkata'=>'Kolkata','durgapur'=>'Durgapur');


$countryArray = array('australia'=>'Australia','usa'=>'USA','uk'=>'United Kingdom','india'=>'India','brazil'=>'Brazil','japan'=>'Japan','Canada'=>'Canada','newzeland'=>'Newzeland','sa'=>'Saudi Arab');


$industryArray = array('it'=>'IT-Software/Software Services','accounting'=>'Accounting/Finance','fresher'=>'Fresher/Trainee','banking'=>'Banking/Financial Services/Broking','construction'=>'Construction/Engineering/Cement/Metals','advertising'=>'Advertising/PR/MR/Events','agriculture'=>'Agriculture/Dairy','animation'=>'Animation','interior'=>'Architecture/Interior Designing','auto'=>'Auto/Auto Ancillary','aviation'=>'Aviation / Aerospace Firms','bpo'=>'BPO/ITES','brewery'=>'Brewery / Distillery','ceramics'=>'Ceramics /Sanitary ware','chemical'=>'Chemicals/PetroChemical/Plastic/Rubber','consumer'=>'Consumer Durables','courier'=>'Courier/Transportation/Freight','defence'=>'Defence/Government','education'=>'Education/Teaching/Training','electrical'=>'Electricals / Switchgears','export'=>'Export/Import','facility'=>'Facility Management','fertilizer'=>'Fertilizers/Pesticides','fmcg'=>'FMCG/Foods/Beverage','food'=>'Food Processing','gems'=>'Gems & Jewellery','glass'=>'Glass','heat'=>'Heat Ventilation Air Conditioning','hotels'=>'Hotels/Restaurants/Airlines/Travel','industrial'=>'Industrial Products/Heavy Machinery','insurance'=>'Insurance','it-hard'=>'IT-Hardware & Networking','kpo'=>'KPO / Research /Analytics','legal'=>'Legal','media'=>'Media/Dotcom/Entertainment','medical'=>'Medical/Healthcare/Hospital','mining'=>'Mining','ngo'=>'NGO/Social Services','office'=>'Office Equipment/Automation','oil'=>'Oil and Gas/Power/Infrastructure/Energy','paper'=>'Paper','pharma'=>'Pharma/Biotech/Clinical Research','printing'=>'Printing/Packaging','publishing'=>'Publishing','estate'=>'Real Estate/Property','recruitment'=>'Recruitment','retail'=>'Retail','security'=>'Security/Law Enforcement','electronics'=>'Semiconductors/Electronics','shipping'=>'Shipping/Marine','steel'=>'Steel','strategy'=>'Strategy /Management Consulting Firms','telecom'=>'Telcom/ISP','textiles'=>'Textiles/Garments/Accessories','tyres'=>'Tyres','water'=>'Water Treatment / Waste Management','wellness'=>'Wellness/Fitness/Sports','other'=>'Other');



$functionalAreaArray = array('accounts'=>'Accounts / Finance / Tax / CS / Audit','production'=>'Production / Maintenance / Quality','itsoftware'=>'IT Software- Application Programming / Maintenance','ites'=>'ITES / BPO / KPO / Customer Service / Operations','banking'=>'Banking / Insurance','agent'=>'Agent','interior'=>'Architecture / Interior Design','journalism'=>'Content / Journalism','corporate'=>'Corporate Planning / Consulting','engineering'=>'Engineering Design / R&D','export'=>'Export / Import / Merchandising','fashion'=>'Fashion / Garments / Merchandising','security'=>'Guards / Security Services','hotels'=>'Hotels / Restaurants','hr'=>'HR / Administration / IR','server'=>'IT Software - Client Server','mainframe'=>'IT Software - Mainframe','middleware'=>'IT Software - Middleware','mobile'=>'IT Software - Mobile','softother'=>'IT Software - Other','system'=>'IT Software - System Programming','telecom'=>'IT Software - Telecom Software','dba'=>'IT Software- DBA / Datawarehousing','ecommerce'=>'IT Software- E-Commerce / Internet Technologies','embedded'=>'IT Software- Embedded /EDA /VLSI /ASIC /Chip Des.','erp'=>'IT Software- ERP / CRM','network'=>'IT Software- Network Administration / Security','testing'=>'IT Software- QA & Testing','mis'=>'IT Software- Systems / EDP / MIS','hardware'=>'IT- Hardware / Telecom / Technical Staff / Support','legal'=>'Legal','marketing'=>'Marketing / Advertising / MR / PR','packaging'=>'Packaging','pharma'=>'Pharma / Biotech / Healthcare / Medical / R&D','purchase'=>'Purchase / Logistics / Supply Chain','sales'=>'Sales / BD','secretary'=>'Secretary / Front Office / Data Entry','self'=>'Self Employed / Consultants','site'=>'Site Engineering / Project Management','education'=>'Teaching / Education','travel'=>'Ticketing / Travel / Airlines','mgmt'=>'Top Management','tv'=>'TV / Films / Production','design'=>'Web / Graphic Design / Visualiser','other'=>'Other');



$graduationArray = array('1'=>'Not Pursuing Graduation','2'=>'B.A','3'=>'B.Arch','4'=>'BCA','5'=>'B.B.A','6'=>'B.Com','7'=>'B.Ed','8'=>'BDS','9'=>'BHM','10'=>'B.Pharma','11'=>'B.Sc','12'=>'B.Tech/B.E.','13'=>'LLB','14'=>'MBBS','15'=>'Diploma','16'=>'BVSC','17'=>'Other');
?>